controller_list:
  - name: fake_gripper_controller
    joints:
      - left_gripper_finger_joint
      - right_gripper_finger_joint
  - name: fake_kuka_arm_controller
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
initial:  # Define initial robot poses.
  - group: gripper
    pose: initial_pose_openGripper